# Rishi Raj      22M0033

In [1]:
import numpy as np
import pandas as pd

In [2]:
samples_num = 12
feature_dimension = 5
weight_vector = np.random.randint(-10,10,size=(feature_dimension,1))
bias_vector = np.random.randint(1,size=(samples_num,1))
noise = np.random.randint(0,10,size=(samples_num,1))
variance = np.random.randint(9,10,size=(samples_num,1))
def data_matrix_generator(a,b):
    random_array=np.random.randint(0, 100, size=(a,b))
    def normalizer(a):
        x_normed = a/ a.max(axis=0) #https://stackoverflow.com/questions/29661574/normalize-numpy-array-columns-in-python
        return x_normed
    return pd.DataFrame(normalizer(random_array))
data_matrix = data_matrix_generator(samples_num,feature_dimension)
data_matrix   

0         1         2         3         4
0   0.847059  1.000000  0.541667  0.969072  0.577320
1   0.658824  0.910112  0.260417  0.123711  0.608247
2   0.847059  0.157303  0.020833  0.494845  0.113402
3   0.741176  0.966292  0.177083  0.835052  0.608247
4   0.341176  0.617978  0.281250  0.164948  0.164948
5   1.000000  0.640449  0.322917  0.103093  0.814433
6   0.047059  0.146067  0.229167  1.000000  1.000000
7   0.023529  0.662921  1.000000  0.917526  0.731959
8   0.400000  0.146067  0.739583  0.268041  0.649485
9   0.117647  0.213483  0.604167  0.680412  0.711340
10  0.800000  0.292135  0.093750  0.247423  0.216495
11  0.600000  0.898876  0.697917  0.371134  0.989691

In [3]:
def target_column_vector_generator(a,b,c,d,e):
    target_vector= np.dot(a,b)+c+d+e
    return target_vector 
target_vector=target_column_vector_generator(data_matrix,weight_vector,bias_vector,noise,variance)
    

In [4]:
target_vector

array([[ 7.67787548],
       [ 9.51373881],
       [ 5.85305116],
       [ 9.98440495],
       [14.37267573],
       [ 7.85711562],
       [-0.05151465],
       [ 8.44998739],
       [11.23250849],
       [ 4.352745  ],
       [ 8.09624551],
       [ 2.15216369]])

In [5]:
def linear_regression_estimate(p,q,r):
    weight_vector=np.random.randint(0,5,size=(feature_dimension,1))
    bias_vector=np.random.randint(1,size=(samples_num,1))
    for i in range(0,feature_dimension):
        p[p.columns[i]] = p[p.columns[i]].apply(lambda x: x**(i+1))
    predcited_values_vector=np.matmul(p,q)+r
    return predcited_values_vector , p
predicted_values=linear_regression_estimate(data_matrix,weight_vector,bias_vector)
predicted_vector=predicted_values[0]
predicted_vector
transformed_data_matrix=predicted_values[1]
transformed_data_matrix

0         1         2         3         4
0   0.847059  1.000000  0.158927  0.881910  0.064133
1   0.658824  0.828305  0.017661  0.000234  0.083253
2   0.847059  0.024744  0.000009  0.059962  0.000019
3   0.741176  0.933720  0.005553  0.486243  0.083253
4   0.341176  0.381896  0.022247  0.000740  0.000122
5   1.000000  0.410175  0.033672  0.000113  0.358325
6   0.047059  0.021336  0.012035  1.000000  1.000000
7   0.023529  0.439465  1.000000  0.708717  0.210103
8   0.400000  0.021336  0.404540  0.005162  0.115570
9   0.117647  0.045575  0.220531  0.214333  0.182132
10  0.800000  0.085343  0.000824  0.003748  0.000476
11  0.600000  0.807979  0.339947  0.018972  0.949506

In [6]:
def mean_square_error(a,b):
    error=((a-b).apply(lambda x: x**2).sum())/(2*samples_num)
    return error
MSE=mean_square_error(predicted_vector,target_vector)
MSE 

0    48.381898
dtype: float64

In [7]:
lambda_values=[10,1,0.01,0.001,0.0001,0.00001,0.000001]
def weight_estimation(a,b,c):
    optimized_weight_list = []
    optimized_prediction_list = []
    optimized_MSE_list = []
    for i in range(len(lambda_values)):
        optimized_weights1 = np.linalg.inv(a[i]*np.identity(feature_dimension)+np.matmul(np.transpose(b),b))
        optimized_weights2 = np.matmul(np.transpose(b),c)
        optimized_weights = np.matmul(optimized_weights1,optimized_weights2)
        optimized_weight_list.append(optimized_weights)
        optimized_prediction = np.matmul(transformed_data_matrix,optimized_weights)+bias_vector
        optimized_prediction_list.append(optimized_prediction)
        optimized_mean_square_error = ((optimized_prediction-c).apply(lambda x: x**2).sum())/(2*samples_num)
        optimized_MSE_list.append(optimized_mean_square_error[0])
        min_MSE_position = optimized_MSE_list.index(min(optimized_MSE_list))#https://www.geeksforgeeks.org/python-maximum-minimum-elements-position-list/
    return optimized_weight_list[min_MSE_position], optimized_prediction_list[min_MSE_position] ,optimized_MSE_list[min_MSE_position]
OUTPUT=weight_estimation(lambda_values,transformed_data_matrix,target_vector)
optimal_weight,optimal_prediction,optimal_MSE=OUTPUT[0],OUTPUT[1],OUTPUT[2]
    
    
    

C:\Users\MOHIT PRAJAPAT\AppData\Local\Temp\ipykernel_18476\959657677.py:7: FutureWarning: Calling a ufunc on non-aligned DataFrames (or DataFrame/Series combination). Currently, the indices are ignored and the result takes the index/columns of the first DataFrame. In the future , the DataFrames/Series will be aligned before applying the ufunc.
Convert one of the arguments to a NumPy array (eg 'ufunc(df1, np.asarray(df2)') to keep the current behaviour, or align manually (eg 'df1, df2 = df1.align(df2)') before passing to the ufunc to obtain the future behaviour and silence this warning.
  optimized_weights1 = np.linalg.inv(a[i]*np.identity(feature_dimension)+np.matmul(np.transpose(b),b))
C:\Users\MOHIT PRAJAPAT\AppData\Local\Temp\ipykernel_18476\959657677.py:11: FutureWarning: Calling a ufunc on non-aligned DataFrames (or DataFrame/Series combination). Currently, the indices are ignored and the result takes the index/columns of the first DataFrame. In the future , the DataFrames/Series 

In [8]:
optimal_MSE

7.460774597092588

In [9]:
def mse_gradient_weight(a,b,c,d):
    gradient = (np.dot(a.T, np.matmul(a,b)+c-d) / len(d)).sum()
    return gradient
MSE_gradient = mse_gradient_weight(transformed_data_matrix,weight_vector,bias_vector,target_vector)

In [10]:
MSE_gradient

-15.71876159408501

In [11]:
def L2_norm(w):
    l2_norm=np.matmul(w.T,w)/2
    return l2_norm
L2_NORM=L2_norm(weight_vector)

In [12]:
L2_NORM

array([[64.]])

In [13]:
def L2_norm_gradient(w):
    gradient= w
    return pd.DataFrame(gradient)
l2_norm_gradient=L2_norm_gradient(weight_vector)
    

In [14]:
l2_norm_gradient

0
0  -2
1   4
2   2
3  -2
4 -10

In [15]:
def L1_norm(w):
    norm = pd.DataFrame(w).abs().sum() #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.abs.html
    return norm
l1_norm = L1_norm(weight_vector)
l1_norm

0    20
dtype: int64

In [16]:
def L1_norm_gradient(w):
    dummy_weight_vector=np.random.randint(0,5,size=(feature_dimension,1))
    for i in range(feature_dimension):
        if w[i][0]>0:
            dummy_weight_vector[i][0]=1
        elif w[i][0]<0:
            dummy_weight_vector[i][0]=-1
        elif w[i][0]==0:
            dummy_weight_vector[i][0]=0
    return dummy_weight_vector
L1_gradient = L1_norm_gradient(weight_vector)

    

In [17]:
L1_gradient

array([[-1],
       [ 1],
       [ 1],
       [-1],
       [-1]])

In [18]:
def gradient_descent(X, t, w, eta, lambda_2, lambda_1):
    gradient_value = np.dot(X.T, np.matmul(X,w)-t) / len(t) + lambda_2*w+ lambda_1*L1_norm_gradient(w)
    newly_optimized_weight_vector = w-eta*gradient_value
    new_mean_squared_error = (pd.DataFrame((np.dot(X,newly_optimized_weight_vector)-t)).apply(lambda x: x**2).sum())/(2*samples_num)
    return newly_optimized_weight_vector , new_mean_squared_error 
output_gd= gradient_descent(transformed_data_matrix,target_vector,weight_vector,0.01,0.00001,0.00001)
updated_weight_vector,updated_MSE =output_gd[0] ,output_gd[1]
    
    